2022-03-30 08:33:13,652 - instabot version: 0.117.0 (bot) - INFO - Instabot version: 0.117.0 Started
2022-03-30 08:33:13,653 - instabot version: 0.117.0 (bot) - DEBUG - Bot imported from C:\Users\Jordf\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\instabot\bot\bot.py
2022-03-30 08:33:13,655 - instabot version: 0.117.0 (api_login) - INFO - Not yet logged in starting: PRE-LOGIN FLOW!
2022-03-30 08:33:13,808 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/get_prefill_candidates/ returned response: <Response [200]>
2022-03-30 08:33:13,965 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: qe/sync/ returned response: <Response [200]>
2022-03-30 08:33:14,103 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: launcher/sync/ returned response: <Response [200]>
2022-03-30 08:33:14,227 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/contact_point_prefill/ returned response: <Response [429]>
2022-03-30 08:33:14,228 - instabot version: 0.117.0 (api) - DEBUG - Responsecode indicates error; response content: b'{"message":"Please wait a few minutes before you try again.","status":"fail"}'
2022-03-30 08:33:14,228 - instabot version: 0.117.0 (api) - ERROR - Request returns 429 error!
2022-03-30 08:33:14,230 - instabot version: 0.117.0 (api) - WARNING - That means 'too many requests'. I'll go to sleep for 5 minutes.
