2022-03-30 08:24:40,099 - instabot version: 0.117.0 (bot) - INFO - Instabot version: 0.117.0 Started
2022-03-30 08:24:40,100 - instabot version: 0.117.0 (bot) - DEBUG - Bot imported from C:\Users\Jordf\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\instabot\bot\bot.py
2022-03-30 08:24:40,100 - instabot version: 0.117.0 (api_login) - INFO - Not yet logged in starting: PRE-LOGIN FLOW!
2022-03-30 08:24:40,285 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/get_prefill_candidates/ returned response: <Response [200]>
2022-03-30 08:24:40,460 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: qe/sync/ returned response: <Response [200]>
2022-03-30 08:24:40,611 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: launcher/sync/ returned response: <Response [200]>
2022-03-30 08:24:40,757 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/contact_point_prefill/ returned response: <Response [200]>
2022-03-30 08:24:44,089 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/login/ returned response: <Response [400]>
2022-03-30 08:24:44,093 - instabot version: 0.117.0 (api) - DEBUG - Responsecode indicates error; response content: b'{"message":"challenge_required","challenge":{"url":"https://i.instagram.com/challenge/AXEUVT82P8L50uQWR2E4hwcrdAKVxqz-XgkuH4f_NyQr7Aez0mYmbZTYDEfTDbUVuw1DuGU/oVyFn4Hbrj9kcAhs/","api_path":"/challenge/AXEUVT82P8L50uQWR2E4hwcrdAKVxqz-XgkuH4f_NyQr7Aez0mYmbZTYDEfTDbUVuw1DuGU/oVyFn4Hbrj9kcAhs/","hide_webview_header":true,"lock":true,"logout":false,"native_flow":true,"flow_render_type":0},"status":"fail","error_type":"checkpoint_challenge_required"}'
2022-03-30 08:24:44,093 - instabot version: 0.117.0 (api) - ERROR - Request returns 400 error!
2022-03-30 08:24:44,093 - instabot version: 0.117.0 (api) - INFO - Instagram's error message: challenge_required
2022-03-30 08:24:44,094 - instabot version: 0.117.0 (api) - INFO - Error type: checkpoint_challenge_required
2022-03-30 08:27:13,188 - instabot version: 0.117.0 (bot) - INFO - Instabot version: 0.117.0 Started
2022-03-30 08:27:13,189 - instabot version: 0.117.0 (bot) - DEBUG - Bot imported from C:\Users\Jordf\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\instabot\bot\bot.py
2022-03-30 08:27:13,191 - instabot version: 0.117.0 (api_login) - INFO - Not yet logged in starting: PRE-LOGIN FLOW!
2022-03-30 08:27:14,480 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/get_prefill_candidates/ returned response: <Response [200]>
2022-03-30 08:27:15,357 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: qe/sync/ returned response: <Response [200]>
2022-03-30 08:27:16,553 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: launcher/sync/ returned response: <Response [200]>
2022-03-30 08:27:18,956 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/contact_point_prefill/ returned response: <Response [429]>
2022-03-30 08:27:18,956 - instabot version: 0.117.0 (api) - DEBUG - Responsecode indicates error; response content: b'{"message":"Please wait a few minutes before you try again.","status":"fail"}'
2022-03-30 08:27:18,956 - instabot version: 0.117.0 (api) - ERROR - Request returns 429 error!
2022-03-30 08:27:18,957 - instabot version: 0.117.0 (api) - WARNING - That means 'too many requests'. I'll go to sleep for 5 minutes.
